### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by BookOwl** [TheMonsterFromTheDeep/pop#2]
Whenever I try to use pop to edit a file that already exists, I just get `Segmentation fault: 11`
If the file doesn't already exist pop starts up, but as soon as a hit a key it crashes:
<img width="655" alt="untitled" src="https://cloud.githubusercontent.com/assets/13385064/22214726/c7e02d4a-e166-11e6-888f-6ac9a75b4c96.png">

I'm on OS X 10.11

**Comment by TheMonsterFromTheDeep** [comment]
Oh boy this one is going to be fun to debug

Hopefully I can get the error to occur on my system because otherwise I'll have a really hard time tracking it down

**Comment by BookOwl** [comment]
This is exactly why I use Rust. :P

**Comment by TheMonsterFromTheDeep** [comment]
But C is more fun :package:

**Comment by TheMonsterFromTheDeep** [comment]
So I'm guessing this bug has something to do with some integer-to-pointer warning gcc keeps giving me. Maybe I can track it down later today.

**Comment by TheMonsterFromTheDeep** [comment]
@BookOwl the main system has changed quite a bit - could you let me know if you still get this error?

**Comment by BookOwl** [comment]
Now it always gives me the file not found message, even if the file exists. When I try to quite with Ctrl-q, it gives me a segmentation fault (11). No other keys seem to do anything.

**Comment by BookOwl** [comment]
Wish I could be a better help, but I'm not very good at debugging C code.

**Comment by TheMonsterFromTheDeep** [comment]
That's strange.

I installed it on cygwin yesterday and got a problem similar to your original problem, and I thought it was because there was a function missing from the zLib header. But I checked and it doesn't look like that was right.

Also, there is no file-not-found message - if a file doesn't exist, it creates it (well, as long as all the correct folders exist).

Do you mean it always just has the "No files are open!" message?

Try running it without any command line arguments and then pushing control-o to load a file and see what that does.

I wish I had a system similar to yours because all this communication is rather cumbersome. :package:

**Comment by BookOwl** [comment]
If I run it without any arguments and then hit Ctrl-o I get a segmentation fault (again!)

**Comment by BookOwl** [comment]
I'm going to try and build this in a debian VM to see if this is just on my machine.

**Comment by BookOwl** [comment]
OK, on my mac, if I run pop without any arguments I can quit pop with Ctrl-q without it crashing, but if I run pop with a command line argument it crashes when I do Ctrl-q

**Comment by TheMonsterFromTheDeep** [comment]
Okay, I think my earlier statement was actually accurate, looking at a few of the warnings gcc is giving me on Cygwin. (for some reason it doesn't show these on ubuntu...)

Basically I forgot to declare zstr_clone in zstr.h, and I forgot to declare buf_init in editor.h. I think if I fix those it should work.

**Comment by BookOwl** [comment]
Well, this is interesting...
<img width="858" alt="untitled" src="https://cloud.githubusercontent.com/assets/13385064/22399393/830c2f46-e569-11e6-939f-4d31582aab89.png">
I ran pop with `./pop test.txt` and typed Ctrl-o

**Comment by TheMonsterFromTheDeep** [comment]
Okay so try updating your code again (you'll have to do `make setup` again as well). I know that it's working on cygwin now so maybe it will work for you?

**Comment by BookOwl** [comment]
It still does the same thing.

**Comment by TheMonsterFromTheDeep** [comment]
Hmm. :/ Just to be sure, can you try building a completely clean copy?

Looking at gcc warning output on cygwin (which doesn't show up on ubuntu even with -Wall) it looks like it is probably a problem with zlist_add.

**Comment by BookOwl** [comment]
I finally got my debian vm setup, and it works there

**Comment by BookOwl** [comment]
Nice editor by the way

**Comment by TheMonsterFromTheDeep** [comment]
thanks. :)

**Comment by BookOwl** [comment]
Ok, I recloned the repo into another directory and built it there. It still crashes. :(
(in OSX)

**Comment by BookOwl** [comment]
here are the warnings clang generated:
```
clang: warning: -lzlib: 'linker' input unused
clang: warning: argument unused during compilation: '-Lzlib'
src/main.c:152:17: warning: unsequenced modification and access to 'buffers' [-Wunsequenced]
                zlist_add(buffers, nbuf);
                ^         ~~~~~~~
zlib/zlib/zlist.h:27:11: note: expanded from macro 'zlist_add'
    ((name=zlist_add_(name,sizeof(*name)))[zsize(name)-1]=(value))
          ^                                      ~~~~
src/main.c:200:9: warning: unsequenced modification and access to 'buffers' [-Wunsequenced]
        zlist_add(buffers, nbuf);
        ^         ~~~~~~~
zlib/zlib/zlist.h:27:11: note: expanded from macro 'zlist_add'
    ((name=zlist_add_(name,sizeof(*name)))[zsize(name)-1]=(value))
          ^                                      ~~~~
2 warnings generated.
mkdir -p build
cc -MMD -c src/editor.c -o build/editor.o -Izlib -Lzlib -lncurses -lzlib
clang: warning: -lncurses: 'linker' input unused
clang: warning: -lzlib: 'linker' input unused
clang: warning: argument unused during compilation: '-Lzlib'
cc build/main.o build/editor.o -o pop -Izlib -Lzlib -lncurses -lzlib
```

**Comment by BookOwl** [comment]
Here is the output of `make setup`:
```
rm -rf zlib
mkdir -p zlib
git clone https://github.com/TheMonsterFromTheDeep/zlib zlib
Cloning into 'zlib'...
remote: Counting objects: 113, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 113 (delta 2), reused 0 (delta 0), pack-reused 106
Receiving objects: 100% (113/113), 27.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (64/64), done.
Checking connectivity... done.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C zlib
mkdir -p build
cc -MMD -c src/zstr.c -o build/zstr.o -Wall
src/zstr.c:205:19: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if(zsize(str) < 0) { *zsizeptr(str) = 0; }
       ~~~~~~~~~~ ^ ~
1 warning generated.
mkdir -p build
cc -MMD -c src/zlist.c -o build/zlist.o -Wall
mkdir -p build
cc -MMD -c src/zexception.c -o build/zexception.o -Wall
mkdir -p build
cc -MMD -c src/zdata.c -o build/zdata.o -Wall
#gcc -shared -Wl,-soname, \
	#-o  ./build/zstr.o ./build/zlist.o ./build/zexception.o ./build/zdata.o -lc
ar rcs ./build/libzlib.a ./build/zstr.o ./build/zlist.o ./build/zexception.o ./build/zdata.o
cd zlib && cp build/libzlib.a libzlib.a
cd zlib && mv src zlib
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C zlib clean
rm -rf ./build
```

**Comment by TheMonsterFromTheDeep** [comment]
oh shoot yeah that's more helpful

maybe I should use clang if it generates such awesome warning messages

In any case I knew that the problem was approximately that, and I've made some changes to zlib that should fix it, I think. They're rather ugly but until I can come up with a clever way of not getting that error they'll have to stay that way.

**Comment by TheMonsterFromTheDeep** [comment]
@BookOwl do you still get that error?

**Comment by BookOwl** [comment]
Now I can't build it at all:
```
$ make clean
$ make setup
$ make
mkdir -p build
cc -MMD -c src/main.c -o build/main.o -Izlib -Lzlib -lncurses -lzlib
clang: warning: -lncurses: 'linker' input unused
clang: warning: -lzlib: 'linker' input unused
clang: warning: argument unused during compilation: '-Lzlib'
src/main.c:152:17: error: expected ')'
                zlist_add(buffers, nbuf);
                ^
zlib/zlib/zlist.h:28:47: note: expanded from macro 'zlist_add'
        (name)=zlist_add_((name),sizeof(*name);\
                                              ^
src/main.c:152:17: note: to match this '('
zlib/zlib/zlist.h:28:26: note: expanded from macro 'zlist_add'
        (name)=zlist_add_((name),sizeof(*name);\
                         ^
src/main.c:152:17: error: expected ';' after expression
                zlist_add(buffers, nbuf);
                ^
zlib/zlib/zlist.h:29:38: note: expanded from macro 'zlist_add'
        (name)[zsize(name)-1]=(value))\
                                     ^
src/main.c:152:17: error: expected expression
zlib/zlib/zlist.h:29:38: note: expanded from macro 'zlist_add'
        (name)[zsize(name)-1]=(value))\
                                     ^
src/main.c:200:9: error: expected ')'
        zlist_add(buffers, nbuf);
        ^
zlib/zlib/zlist.h:28:47: note: expanded from macro 'zlist_add'
        (name)=zlist_add_((name),sizeof(*name);\
                                              ^
src/main.c:200:9: note: to match this '('
zlib/zlib/zlist.h:28:26: note: expanded from macro 'zlist_add'
        (name)=zlist_add_((name),sizeof(*name);\
                         ^
src/main.c:200:9: error: expected ';' after expression
        zlist_add(buffers, nbuf);
        ^
zlib/zlib/zlist.h:29:38: note: expanded from macro 'zlist_add'
        (name)[zsize(name)-1]=(value))\
                                     ^
src/main.c:200:9: error: expected expression
zlib/zlib/zlist.h:29:38: note: expanded from macro 'zlist_add'
        (name)[zsize(name)-1]=(value))\
                                     ^
6 errors generated.
make: *** [build/main.o] Error 1
```

**Comment by BookOwl** [comment]
Looks like your macro is missing a right parentheses.

**Comment by TheMonsterFromTheDeep** [comment]
I can't believe I forgot to check that. -_-

It should work now.

**Comment by BookOwl** [comment]
It works! 

Have a cookie for your hard work. 🍪
